name: Kodi Addon-Check

on: [push, pull_request]

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: xbmc/action-kodi-addon-checker@v1.1
      with:
        kodi-version: matrix
        is-pr: false
        addon-id: ${{ github.event.repository.name }}


# name: Kodi Addon-Check

# on: [push, pull_request]

# jobs:
#   kodi-addon-checker:
#     runs-on: ubuntu-latest
#     name: Kodi Addon-Checker
#     steps:

#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#         fetch-depth: 0

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip3 install --user kodi-addon-checker
#     - name: Extract job variables
#       shell: bash

#       run: |
#         echo "addon=$(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq)" >> $GITHUB_OUTPUT
#       id: extract_vars

#     - name: Addon-Check
#       run: $HOME/.local/bin/kodi-addon-checker --branch=matrix